Fixes error on update `hasMany` relation with composite key
la-haute-societe/yii2-save-relations-behavior pull request #36
Opened 2018-08-11 12:02 UTC by leandrogehlen

2018-08-11 13:48 UTC, juban reviewed
I copied your test file an ran it using the current version and did not get any failure. What does your patch is trying to fix exactly? Thanks.

2018-08-11 16:27 UTC, juban requested changes
Hi. Thank you for the pull request.
However, could you provide a test case that was failing without your fix please? Thx.

2018-08-13 12:10 UTC, leandrogehlen commented
You are right, the test that i added does not cover the fix.
The problem occurs with ProjectLink relation.

I'am building the correct test.

The follow situation not works: 

```php
$project = Project::findOne(1);
$data = [
    'ProjectLink'    => [
        [
            'language' => 'en',
            'name'     => 'yii',
            'link'     => 'http://www.yiiframework.com'
        ],[
            'language' => 'fr',
            'name'     => 'yii',
            'link'     => 'http://www.yiiframework.fr'
        ], [
           'language' => 'en',
           'name' => 'mac_os_x',
           'link' => 'http://www.apple.com/osx/updated'
       ]
]];

$project->loadRelations($data);
```

2018-08-13 15:48 UTC, juban approved these changes

2018-08-13 15:51 UTC, merged